package com.networkbroadcast.hospitality.brand

/**
 * Textos de interfaz por idioma. El idioma lo elige el huésped al entrar (como hacía
 * HotelLanguageActivity) y no depende del idioma del dispositivo, que en un hotel casi nunca
 * es el del huésped. Por eso no se usan los values-xx de Android.
 */
data class UiText(
    val chooseLanguage: String,
    val goodMorning: String,
    val goodAfternoon: String,
    val goodEvening: String,
    val entertainment: String,
    val liveNow: String,
    val moviesAndSeries: String,
    val quickActions: String,
    val aboutHotel: String,
    val language: String,
    val checkout: String,
    val checkoutQuestion: String,
    val checkoutDetail: String,
    val confirm: String,
    val cancel: String,
    val room: String,
    val loading: String,
    val hotelUnavailable: String,
    val liveTv: String,
    val noChannels: String,
    val guide: String,
    val nowLabel: String,
    val nextLabel: String,
    val watchLive: String,
    val watchAgain: String,
    val noSchedule: String,
    val play: String,
    val noVod: String,
    val minutes: String,
    val playbackError: String,
    // Login de la TV (lo hace el instalador o el staff, una sola vez).
    val loginTitle: String,
    val loginHint: String,
    val loginEyebrow: String,
    val loginTagline: String,
    val loginNote: String,
    val user: String,
    val password: String,
    val enter: String,
    val connecting: String,
    val reconnecting: String,
    val provisioning: String,
    val loginRejected: String,
    val loginTimeout: String,
    val loginDrmError: String,
    val chooseLicense: String,
    val chooseLicenseHint: String,
    val license: String,
    val messageTitle: String,
    val accept: String,
    val welcomeTitle: String,
    val welcomeTitleNoName: String,
    val start: String,
    val pairPhone: String,
    val pairTitle: String,
    val pairHint: String,
    val connectTv: String,
    val connectHint: String,
    val code: String,
    val connect: String,
    val connectedTo: String,
    val disconnect: String,
    val invalidCode: String,
    val linkFailed: String,
    val onTheTv: String,
    val openGuideOnTv: String,
    val openHotelOnTv: String,
    val sentToTv: String,
    val demoNote: String,
) {
    companion object {
        private val es = UiText(
            chooseLanguage = "Elegí tu idioma",
            goodMorning = "Buenos días", goodAfternoon = "Buenas tardes", goodEvening = "Buenas noches",
            entertainment = "Entretenimiento", liveNow = "En vivo ahora", moviesAndSeries = "Películas y series",
            quickActions = "Acciones rápidas", aboutHotel = "Acerca del hotel", language = "Idioma",
            checkout = "Check-out", checkoutQuestion = "¿Terminar la estadía en esta TV?",
            checkoutDetail = "Se borran tus datos en esta TV (idioma y celular conectado) y queda lista para el próximo huésped.",
            confirm = "Confirmar", cancel = "Cancelar", room = "Hab.", loading = "Cargando…",
            hotelUnavailable = "No se pudo cargar la información del hotel.",
            liveTv = "TV en vivo",
            noChannels = "No hay canales disponibles para esta TV.",
            guide = "Guía",
            nowLabel = "Ahora",
            nextLabel = "Después",
            watchLive = "Ver en vivo",
            watchAgain = "Ver de nuevo",
            noSchedule = "Sin programación para este canal.",
            play = "Reproducir",
            noVod = "No hay películas ni series disponibles.",
            minutes = "min",
            playbackError = "No se pudo reproducir este canal.",
            loginTitle = "Configurar esta TV",
            loginHint = "Ingresá la cuenta de TV del hotel. Se pide una sola vez.",
            loginEyebrow = "Configuración inicial",
            loginTagline = "Sistema de TV de la habitación",
            loginNote = "La sesión queda guardada en esta TV. Solo el personal del hotel necesita estos datos.",
            user = "Usuario",
            password = "Contraseña",
            enter = "Entrar",
            connecting = "Conectando…",
            reconnecting = "Sin conexión con el servicio de TV. Reintentando…",
            provisioning = "Configurando esta TV con el archivo del instalador…",
            loginRejected = "Usuario o contraseña incorrectos.",
            loginTimeout = "El servidor no respondió. Revisá la conexión.",
            loginDrmError = "No se pudo iniciar el servicio de TV.",
            chooseLicense = "Elegí la licencia de esta TV",
            chooseLicenseHint = "Ninguna se pudo tomar sola (puede estar en uso en otra TV). Si elegís una en uso, pasa a esta TV.",
            license = "Licencia",
            messageTitle = "Mensaje",
            accept = "Aceptar",
            welcomeTitle = "Te damos la bienvenida, %s",
            welcomeTitleNoName = "Te damos la bienvenida",
            start = "Comenzar",
            pairPhone = "Conectar celular",
            pairTitle = "Conectá tu celular",
            pairHint = "Abrí la app del hotel en tu celular e ingresá este código.",
            connectTv = "Conectar con la TV",
            connectHint = "Ingresá el código que aparece en la TV de tu habitación.",
            code = "Código",
            connect = "Conectar",
            connectedTo = "Conectado a",
            disconnect = "Desconectar",
            invalidCode = "El código tiene que tener 6 números.",
            linkFailed = "No se pudo conectar. Probá de nuevo.",
            onTheTv = "En la TV",
            openGuideOnTv = "Abrir la guía",
            openHotelOnTv = "Ver el hotel en la TV",
            sentToTv = "Enviado a la TV",
            demoNote = "Modo de prueba: la conexión real con la TV llega con el backend.",
        )
        private val en = UiText(
            chooseLanguage = "Choose your language",
            goodMorning = "Good morning", goodAfternoon = "Good afternoon", goodEvening = "Good evening",
            entertainment = "Entertainment", liveNow = "Live now", moviesAndSeries = "Movies & series",
            quickActions = "Quick actions", aboutHotel = "About the hotel", language = "Language",
            checkout = "Check-out", checkoutQuestion = "End your stay on this TV?",
            checkoutDetail = "Your details on this TV (language and connected phone) are cleared and it is ready for the next guest.",
            confirm = "Confirm", cancel = "Cancel", room = "Room", loading = "Loading…",
            hotelUnavailable = "Hotel information could not be loaded.",
            liveTv = "Live TV",
            noChannels = "No channels are available for this TV.",
            guide = "Guide",
            nowLabel = "Now",
            nextLabel = "Next",
            watchLive = "Watch live",
            watchAgain = "Watch again",
            noSchedule = "No schedule for this channel.",
            play = "Play",
            noVod = "No movies or series available.",
            minutes = "min",
            playbackError = "This channel could not be played.",
            loginTitle = "Set up this TV",
            loginHint = "Enter the hotel's TV account. Asked only once.",
            loginEyebrow = "Initial setup",
            loginTagline = "In-room TV system",
            loginNote = "The session stays saved on this TV. Only hotel staff need these details.",
            user = "User",
            password = "Password",
            enter = "Sign in",
            connecting = "Connecting…",
            reconnecting = "No connection to the TV service. Retrying…",
            provisioning = "Setting up this TV with the installer file…",
            loginRejected = "Wrong user or password.",
            loginTimeout = "The server did not answer. Check the connection.",
            loginDrmError = "The TV service could not start.",
            chooseLicense = "Choose this TV's license",
            chooseLicenseHint = "None could be taken automatically (it may be in use on another TV). Choosing one in use moves it to this TV.",
            license = "License",
            messageTitle = "Message",
            accept = "OK",
            welcomeTitle = "Welcome, %s",
            welcomeTitleNoName = "Welcome",
            start = "Get started",
            pairPhone = "Connect phone",
            pairTitle = "Connect your phone",
            pairHint = "Open the hotel app on your phone and enter this code.",
            connectTv = "Connect to the TV",
            connectHint = "Enter the code shown on your room's TV.",
            code = "Code",
            connect = "Connect",
            connectedTo = "Connected to",
            disconnect = "Disconnect",
            invalidCode = "The code must have 6 digits.",
            linkFailed = "Could not connect. Try again.",
            onTheTv = "On the TV",
            openGuideOnTv = "Open the guide",
            openHotelOnTv = "Show the hotel on the TV",
            sentToTv = "Sent to the TV",
            demoNote = "Test mode: the real TV connection comes with the backend.",
        )
        private val pt = UiText(
            chooseLanguage = "Escolha seu idioma",
            goodMorning = "Bom dia", goodAfternoon = "Boa tarde", goodEvening = "Boa noite",
            entertainment = "Entretenimento", liveNow = "Ao vivo agora", moviesAndSeries = "Filmes e séries",
            quickActions = "Ações rápidas", aboutHotel = "Sobre o hotel", language = "Idioma",
            checkout = "Check-out", checkoutQuestion = "Encerrar a estadia nesta TV?",
            checkoutDetail = "Seus dados nesta TV (idioma e celular conectado) são apagados e ela fica pronta para o próximo hóspede.",
            confirm = "Confirmar", cancel = "Cancelar", room = "Quarto", loading = "Carregando…",
            hotelUnavailable = "Não foi possível carregar as informações do hotel.",
            liveTv = "TV ao vivo",
            noChannels = "Não há canais disponíveis para esta TV.",
            guide = "Guia",
            nowLabel = "Agora",
            nextLabel = "Depois",
            watchLive = "Ver ao vivo",
            watchAgain = "Ver de novo",
            noSchedule = "Sem programação para este canal.",
            play = "Reproduzir",
            noVod = "Não há filmes nem séries disponíveis.",
            minutes = "min",
            playbackError = "Não foi possível reproduzir este canal.",
            loginTitle = "Configurar esta TV",
            loginHint = "Informe a conta de TV do hotel. Pedido só uma vez.",
            loginEyebrow = "Configuração inicial",
            loginTagline = "Sistema de TV do quarto",
            loginNote = "A sessão fica salva nesta TV. Só a equipe do hotel precisa destes dados.",
            user = "Usuário",
            password = "Senha",
            enter = "Entrar",
            connecting = "Conectando…",
            reconnecting = "Sem conexão com o serviço de TV. Tentando de novo…",
            provisioning = "Configurando esta TV com o arquivo do instalador…",
            loginRejected = "Usuário ou senha incorretos.",
            loginTimeout = "O servidor não respondeu. Verifique a conexão.",
            loginDrmError = "Não foi possível iniciar o serviço de TV.",
            chooseLicense = "Escolha a licença desta TV",
            chooseLicenseHint = "Nenhuma pôde ser usada automaticamente (pode estar em uso em outra TV). Escolher uma em uso a passa para esta TV.",
            license = "Licença",
            messageTitle = "Mensagem",
            accept = "Aceitar",
            welcomeTitle = "Boas-vindas, %s",
            welcomeTitleNoName = "Boas-vindas",
            start = "Começar",
            pairPhone = "Conectar celular",
            pairTitle = "Conecte seu celular",
            pairHint = "Abra o app do hotel no celular e digite este código.",
            connectTv = "Conectar à TV",
            connectHint = "Digite o código que aparece na TV do seu quarto.",
            code = "Código",
            connect = "Conectar",
            connectedTo = "Conectado a",
            disconnect = "Desconectar",
            invalidCode = "O código deve ter 6 números.",
            linkFailed = "Não foi possível conectar. Tente de novo.",
            onTheTv = "Na TV",
            openGuideOnTv = "Abrir o guia",
            openHotelOnTv = "Ver o hotel na TV",
            sentToTv = "Enviado para a TV",
            demoNote = "Modo de teste: a conexão real com a TV chega com o backend.",
        )
        private val fr = UiText(
            chooseLanguage = "Choisissez votre langue",
            goodMorning = "Bonjour", goodAfternoon = "Bon après-midi", goodEvening = "Bonsoir",
            entertainment = "Divertissement", liveNow = "En direct", moviesAndSeries = "Films et séries",
            quickActions = "Actions rapides", aboutHotel = "À propos de l'hôtel", language = "Langue",
            checkout = "Check-out", checkoutQuestion = "Terminer le séjour sur cette TV ?",
            checkoutDetail = "Vos données sur cette TV (langue et téléphone connecté) sont effacées et elle est prête pour le prochain client.",
            confirm = "Confirmer", cancel = "Annuler", room = "Ch.", loading = "Chargement…",
            hotelUnavailable = "Impossible de charger les informations de l'hôtel.",
            liveTv = "TV en direct",
            noChannels = "Aucune chaîne n'est disponible pour cette TV.",
            guide = "Guide",
            nowLabel = "Maintenant",
            nextLabel = "Ensuite",
            watchLive = "Voir en direct",
            watchAgain = "Revoir",
            noSchedule = "Pas de programme pour cette chaîne.",
            play = "Lire",
            noVod = "Aucun film ni série disponible.",
            minutes = "min",
            playbackError = "Impossible de lire cette chaîne.",
            loginTitle = "Configurer cette TV",
            loginHint = "Saisissez le compte TV de l'hôtel. Demandé une seule fois.",
            loginEyebrow = "Configuration initiale",
            loginTagline = "Système TV de la chambre",
            loginNote = "La session reste enregistrée sur cette TV. Seul le personnel de l'hôtel a besoin de ces informations.",
            user = "Utilisateur",
            password = "Mot de passe",
            enter = "Se connecter",
            connecting = "Connexion…",
            reconnecting = "Pas de connexion au service TV. Nouvel essai…",
            provisioning = "Configuration de cette TV avec le fichier de l'installateur…",
            loginRejected = "Utilisateur ou mot de passe incorrect.",
            loginTimeout = "Le serveur n'a pas répondu. Vérifiez la connexion.",
            loginDrmError = "Le service TV n'a pas pu démarrer.",
            chooseLicense = "Choisissez la licence de cette TV",
            chooseLicenseHint = "Aucune n'a pu être prise automatiquement (elle peut être utilisée sur une autre TV). En choisir une utilisée la transfère sur cette TV.",
            license = "Licence",
            messageTitle = "Message",
            accept = "OK",
            welcomeTitle = "Bienvenue, %s",
            welcomeTitleNoName = "Bienvenue",
            start = "Commencer",
            pairPhone = "Connecter le téléphone",
            pairTitle = "Connectez votre téléphone",
            pairHint = "Ouvrez l'app de l'hôtel sur votre téléphone et saisissez ce code.",
            connectTv = "Se connecter à la TV",
            connectHint = "Saisissez le code affiché sur la TV de votre chambre.",
            code = "Code",
            connect = "Connecter",
            connectedTo = "Connecté à",
            disconnect = "Déconnecter",
            invalidCode = "Le code doit comporter 6 chiffres.",
            linkFailed = "Connexion impossible. Réessayez.",
            onTheTv = "Sur la TV",
            openGuideOnTv = "Ouvrir le guide",
            openHotelOnTv = "Voir l'hôtel sur la TV",
            sentToTv = "Envoyé à la TV",
            demoNote = "Mode test : la vraie connexion à la TV arrive avec le backend.",
        )
        private val de = UiText(
            chooseLanguage = "Wählen Sie Ihre Sprache",
            goodMorning = "Guten Morgen", goodAfternoon = "Guten Tag", goodEvening = "Guten Abend",
            entertainment = "Unterhaltung", liveNow = "Jetzt live", moviesAndSeries = "Filme & Serien",
            quickActions = "Schnellzugriff", aboutHotel = "Über das Hotel", language = "Sprache",
            checkout = "Check-out", checkoutQuestion = "Aufenthalt auf diesem TV beenden?",
            checkoutDetail = "Ihre Daten auf diesem TV (Sprache und verbundenes Handy) werden gelöscht und er ist für den nächsten Gast bereit.",
            confirm = "Bestätigen", cancel = "Abbrechen", room = "Zi.", loading = "Wird geladen…",
            hotelUnavailable = "Hotelinformationen konnten nicht geladen werden.",
            liveTv = "Live-TV",
            noChannels = "Für diesen TV sind keine Sender verfügbar.",
            guide = "Programm",
            nowLabel = "Jetzt",
            nextLabel = "Danach",
            watchLive = "Live ansehen",
            watchAgain = "Erneut ansehen",
            noSchedule = "Kein Programm für diesen Sender.",
            play = "Abspielen",
            noVod = "Keine Filme oder Serien verfügbar.",
            minutes = "Min.",
            playbackError = "Dieser Sender konnte nicht abgespielt werden.",
            loginTitle = "Diesen TV einrichten",
            loginHint = "Geben Sie das TV-Konto des Hotels ein. Nur einmal nötig.",
            loginEyebrow = "Ersteinrichtung",
            loginTagline = "TV-System im Zimmer",
            loginNote = "Die Sitzung bleibt auf diesem TV gespeichert. Nur das Hotelpersonal benötigt diese Daten.",
            user = "Benutzer",
            password = "Passwort",
            enter = "Anmelden",
            connecting = "Verbinde…",
            reconnecting = "Keine Verbindung zum TV-Dienst. Neuer Versuch…",
            provisioning = "Dieser TV wird mit der Installationsdatei eingerichtet…",
            loginRejected = "Benutzer oder Passwort falsch.",
            loginTimeout = "Der Server antwortet nicht. Verbindung prüfen.",
            loginDrmError = "Der TV-Dienst konnte nicht starten.",
            chooseLicense = "Lizenz für diesen TV wählen",
            chooseLicenseHint = "Keine konnte automatisch übernommen werden (evtl. auf einem anderen TV in Benutzung). Eine benutzte zu wählen verschiebt sie auf diesen TV.",
            license = "Lizenz",
            messageTitle = "Nachricht",
            accept = "OK",
            welcomeTitle = "Willkommen, %s",
            welcomeTitleNoName = "Willkommen",
            start = "Los geht's",
            pairPhone = "Handy verbinden",
            pairTitle = "Handy verbinden",
            pairHint = "Öffnen Sie die Hotel-App auf Ihrem Handy und geben Sie diesen Code ein.",
            connectTv = "Mit dem TV verbinden",
            connectHint = "Geben Sie den Code ein, der auf dem TV Ihres Zimmers angezeigt wird.",
            code = "Code",
            connect = "Verbinden",
            connectedTo = "Verbunden mit",
            disconnect = "Trennen",
            invalidCode = "Der Code muss 6 Ziffern haben.",
            linkFailed = "Verbindung fehlgeschlagen. Bitte erneut versuchen.",
            onTheTv = "Auf dem TV",
            openGuideOnTv = "Programm öffnen",
            openHotelOnTv = "Hotel auf dem TV zeigen",
            sentToTv = "An den TV gesendet",
            demoNote = "Testmodus: Die echte TV-Verbindung kommt mit dem Backend.",
        )

        private val byLanguage = mapOf("es" to es, "en" to en, "pt" to pt, "fr" to fr, "de" to de)

        /** Idioma sin textos propios (p. ej. húngaro) -> inglés. */
        fun of(language: String): UiText = byLanguage[language] ?: en

        /** Nombre de cada idioma en su propio idioma, para la pantalla de selección. */
        val languageNames = mapOf(
            "es" to "Español", "en" to "English", "pt" to "Português", "fr" to "Français",
            "de" to "Deutsch", "hu" to "Magyar", "nb" to "Norsk", "sk" to "Slovenčina",
        )
    }
}
