package com.networkbroadcast.hospitality.services

/**
 * Textos de los servicios del hotel, aparte de UiText: los usan también la app del mesero, que no
 * tiene nada más de la TV. Mismos idiomas que UiText (es, en, pt, fr, de). Los que llevan %s se
 * completan con String.format.
 */
data class ServicesText(
    // Huésped (TV y celular)
    val title: String,
    val subtitleTv: String,
    val subtitleMobile: String,
    val myOrders: String,
    val noOrders: String,
    val order: String,
    val quantity: String,
    val total: String,
    val free: String,
    val minutes: String,
    val deliverTo: String,
    /** "Habitación %s" */
    val room: String,
    /** "Número de %s" (camastro, mesa) */
    val spotNumber: String,
    /** "Estás en %s" */
    val youAreAt: String,
    val payment: String,
    /** "Cargar a la habitación %s" */
    val roomCharge: String,
    val card: String,
    val cardSoon: String,
    /** "Confirmo el cargo de %1$s a la habitación %2$s." */
    val confirmCharge: String,
    val placeOrder: String,
    val placing: String,
    val placed: String,
    val placedHint: String,
    val orderFailed: String,
    val connectToOrder: String,
    val notAvailableHere: String,
    val cancelOrder: String,
    val viewOrders: String,
    val keepBrowsing: String,
    /** "Tu pedido de %1$s: %2$s" */
    val statusUpdate: String,
    val demoGuest: String,
    // Estados
    val requested: String,
    val accepted: String,
    val onTheWay: String,
    val delivered: String,
    val cancelled: String,
    // Personal (app del mesero)
    val staffTitle: String,
    val tabNew: String,
    val tabActive: String,
    val tabDone: String,
    val accept: String,
    val startDelivery: String,
    val markDelivered: String,
    /** "Cargo a la habitación %s" */
    val chargeTo: String,
    val paidByCard: String,
    /** "Cargo registrado en la habitación %s" */
    val chargeRegistered: String,
    val guest: String,
    /** "hace %d min" */
    val minutesAgo: String,
    val justNow: String,
    val qrCodes: String,
    val qrHint: String,
    val emptyQueue: String,
    val demoStaff: String,
    val back: String,
) {
    fun status(status: OrderStatus): String = when (status) {
        OrderStatus.Requested -> requested
        OrderStatus.Accepted -> accepted
        OrderStatus.OnTheWay -> onTheWay
        OrderStatus.Delivered -> delivered
        OrderStatus.Cancelled -> cancelled
    }

    companion object {
        fun of(language: String): ServicesText = when (language) {
            "en" -> En
            "pt" -> Pt
            "fr" -> Fr
            "de" -> De
            else -> Es
        }

        val Es = ServicesText(
            title = "Servicios del hotel",
            subtitleTv = "Pedí desde la TV y te lo llevamos a la habitación.",
            subtitleMobile = "Pedí a la habitación o donde estés: piscina, playa.",
            myOrders = "Mis pedidos",
            noOrders = "Todavía no hiciste pedidos.",
            order = "Pedir",
            quantity = "Cantidad",
            total = "Total",
            free = "Sin cargo",
            minutes = "min",
            deliverTo = "¿Dónde te lo llevamos?",
            room = "Habitación %s",
            spotNumber = "Número de %s",
            youAreAt = "Estás en %s",
            payment = "Forma de pago",
            roomCharge = "Cargar a la habitación %s",
            card = "Tarjeta de crédito o débito",
            cardSoon = "Llega con la pasarela de pagos",
            confirmCharge = "Confirmo el cargo de %1\$s a la habitación %2\$s.",
            placeOrder = "Confirmar pedido",
            placing = "Enviando…",
            placed = "¡Pedido enviado!",
            placedHint = "Te avisamos cuando esté en camino.",
            orderFailed = "No se pudo enviar el pedido. Probá de nuevo.",
            connectToOrder = "Conectá tu celular con la TV de tu habitación para pedir.",
            notAvailableHere = "No disponible en esta ubicación",
            cancelOrder = "Cancelar pedido",
            viewOrders = "Ver mis pedidos",
            keepBrowsing = "Seguir viendo",
            statusUpdate = "Tu pedido de %1\$s: %2\$s",
            demoGuest = "Modo de prueba: el pedido avanza solo. Con el backend lo mueve el personal del hotel.",
            requested = "Recibido",
            accepted = "Aceptado",
            onTheWay = "En camino",
            delivered = "Entregado",
            cancelled = "Cancelado",
            staffTitle = "Pedidos",
            tabNew = "Nuevos",
            tabActive = "En curso",
            tabDone = "Entregados",
            accept = "Aceptar",
            startDelivery = "Salir a entregar",
            markDelivered = "Marcar entregado",
            chargeTo = "Cargo a la habitación %s",
            paidByCard = "Pagado con tarjeta",
            chargeRegistered = "Cargo registrado en la habitación %s",
            guest = "Huésped",
            minutesAgo = "hace %d min",
            justNow = "recién",
            qrCodes = "Códigos QR",
            qrHint = "Imprimí cada código y pegalo en su camastro o mesa: el huésped lo escanea y el pedido llega con la ubicación.",
            emptyQueue = "No hay pedidos acá.",
            demoStaff = "Modo de prueba: los pedidos son de ejemplo. Con el backend llegan los de los huéspedes.",
            back = "Volver",
        )

        val En = ServicesText(
            title = "Hotel services",
            subtitleTv = "Order from the TV and we'll bring it to your room.",
            subtitleMobile = "Order to your room or wherever you are: pool, beach.",
            myOrders = "My orders",
            noOrders = "You haven't ordered anything yet.",
            order = "Order",
            quantity = "Quantity",
            total = "Total",
            free = "Free",
            minutes = "min",
            deliverTo = "Where should we bring it?",
            room = "Room %s",
            spotNumber = "%s number",
            youAreAt = "You are at %s",
            payment = "Payment",
            roomCharge = "Charge to room %s",
            card = "Credit or debit card",
            cardSoon = "Coming with the payment gateway",
            confirmCharge = "I confirm the charge of %1\$s to room %2\$s.",
            placeOrder = "Place order",
            placing = "Sending…",
            placed = "Order sent!",
            placedHint = "We'll let you know when it's on the way.",
            orderFailed = "The order couldn't be sent. Please try again.",
            connectToOrder = "Connect your phone to your room's TV to order.",
            notAvailableHere = "Not available at this location",
            cancelOrder = "Cancel order",
            viewOrders = "See my orders",
            keepBrowsing = "Keep browsing",
            statusUpdate = "Your %1\$s order: %2\$s",
            demoGuest = "Test mode: the order moves on its own. With the backend, hotel staff moves it.",
            requested = "Received",
            accepted = "Accepted",
            onTheWay = "On the way",
            delivered = "Delivered",
            cancelled = "Cancelled",
            staffTitle = "Orders",
            tabNew = "New",
            tabActive = "In progress",
            tabDone = "Delivered",
            accept = "Accept",
            startDelivery = "Head out",
            markDelivered = "Mark delivered",
            chargeTo = "Charge to room %s",
            paidByCard = "Paid by card",
            chargeRegistered = "Charge posted to room %s",
            guest = "Guest",
            minutesAgo = "%d min ago",
            justNow = "just now",
            qrCodes = "QR codes",
            qrHint = "Print each code and stick it on its lounger or table: the guest scans it and the order arrives with the location.",
            emptyQueue = "No orders here.",
            demoStaff = "Test mode: these are sample orders. With the backend, guests' orders arrive here.",
            back = "Back",
        )

        val Pt = ServicesText(
            title = "Serviços do hotel",
            subtitleTv = "Peça pela TV e levamos até o seu quarto.",
            subtitleMobile = "Peça no quarto ou onde estiver: piscina, praia.",
            myOrders = "Meus pedidos",
            noOrders = "Você ainda não fez pedidos.",
            order = "Pedir",
            quantity = "Quantidade",
            total = "Total",
            free = "Sem custo",
            minutes = "min",
            deliverTo = "Onde levamos?",
            room = "Quarto %s",
            spotNumber = "Número da %s",
            youAreAt = "Você está em %s",
            payment = "Forma de pagamento",
            roomCharge = "Cobrar no quarto %s",
            card = "Cartão de crédito ou débito",
            cardSoon = "Chega com o gateway de pagamentos",
            confirmCharge = "Confirmo a cobrança de %1\$s no quarto %2\$s.",
            placeOrder = "Confirmar pedido",
            placing = "Enviando…",
            placed = "Pedido enviado!",
            placedHint = "Avisamos quando estiver a caminho.",
            orderFailed = "Não foi possível enviar o pedido. Tente de novo.",
            connectToOrder = "Conecte seu celular à TV do seu quarto para pedir.",
            notAvailableHere = "Indisponível neste local",
            cancelOrder = "Cancelar pedido",
            viewOrders = "Ver meus pedidos",
            keepBrowsing = "Continuar vendo",
            statusUpdate = "Seu pedido de %1\$s: %2\$s",
            demoGuest = "Modo de teste: o pedido avança sozinho. Com o backend, a equipe do hotel o move.",
            requested = "Recebido",
            accepted = "Aceito",
            onTheWay = "A caminho",
            delivered = "Entregue",
            cancelled = "Cancelado",
            staffTitle = "Pedidos",
            tabNew = "Novos",
            tabActive = "Em andamento",
            tabDone = "Entregues",
            accept = "Aceitar",
            startDelivery = "Sair para entregar",
            markDelivered = "Marcar entregue",
            chargeTo = "Cobrança no quarto %s",
            paidByCard = "Pago com cartão",
            chargeRegistered = "Cobrança registrada no quarto %s",
            guest = "Hóspede",
            minutesAgo = "há %d min",
            justNow = "agora",
            qrCodes = "Códigos QR",
            qrHint = "Imprima cada código e cole na espreguiçadeira ou mesa: o hóspede escaneia e o pedido chega com o local.",
            emptyQueue = "Não há pedidos aqui.",
            demoStaff = "Modo de teste: os pedidos são de exemplo. Com o backend chegam os dos hóspedes.",
            back = "Voltar",
        )

        val Fr = ServicesText(
            title = "Services de l'hôtel",
            subtitleTv = "Commandez depuis la TV, nous l'apportons dans votre chambre.",
            subtitleMobile = "Commandez en chambre ou où vous êtes : piscine, plage.",
            myOrders = "Mes commandes",
            noOrders = "Vous n'avez encore rien commandé.",
            order = "Commander",
            quantity = "Quantité",
            total = "Total",
            free = "Gratuit",
            minutes = "min",
            deliverTo = "Où l'apporter ?",
            room = "Chambre %s",
            spotNumber = "Numéro de %s",
            youAreAt = "Vous êtes à %s",
            payment = "Paiement",
            roomCharge = "Facturer sur la chambre %s",
            card = "Carte de crédit ou de débit",
            cardSoon = "Disponible avec la passerelle de paiement",
            confirmCharge = "Je confirme la facturation de %1\$s sur la chambre %2\$s.",
            placeOrder = "Confirmer la commande",
            placing = "Envoi…",
            placed = "Commande envoyée !",
            placedHint = "Nous vous prévenons quand elle est en route.",
            orderFailed = "La commande n'a pas pu être envoyée. Réessayez.",
            connectToOrder = "Connectez votre téléphone à la TV de votre chambre pour commander.",
            notAvailableHere = "Indisponible à cet endroit",
            cancelOrder = "Annuler la commande",
            viewOrders = "Voir mes commandes",
            keepBrowsing = "Continuer",
            statusUpdate = "Votre commande de %1\$s : %2\$s",
            demoGuest = "Mode test : la commande avance toute seule. Avec le backend, le personnel la fait avancer.",
            requested = "Reçue",
            accepted = "Acceptée",
            onTheWay = "En route",
            delivered = "Livrée",
            cancelled = "Annulée",
            staffTitle = "Commandes",
            tabNew = "Nouvelles",
            tabActive = "En cours",
            tabDone = "Livrées",
            accept = "Accepter",
            startDelivery = "Partir livrer",
            markDelivered = "Marquer livrée",
            chargeTo = "Facturé sur la chambre %s",
            paidByCard = "Payé par carte",
            chargeRegistered = "Facturation enregistrée sur la chambre %s",
            guest = "Client",
            minutesAgo = "il y a %d min",
            justNow = "à l'instant",
            qrCodes = "Codes QR",
            qrHint = "Imprimez chaque code et collez-le sur son transat ou sa table : le client le scanne et la commande arrive avec l'emplacement.",
            emptyQueue = "Aucune commande ici.",
            demoStaff = "Mode test : ce sont des commandes d'exemple. Avec le backend, celles des clients arrivent ici.",
            back = "Retour",
        )

        val De = ServicesText(
            title = "Hotelservices",
            subtitleTv = "Bestellen Sie am TV, wir bringen es auf Ihr Zimmer.",
            subtitleMobile = "Bestellen Sie aufs Zimmer oder dorthin, wo Sie sind: Pool, Strand.",
            myOrders = "Meine Bestellungen",
            noOrders = "Sie haben noch nichts bestellt.",
            order = "Bestellen",
            quantity = "Menge",
            total = "Gesamt",
            free = "Kostenlos",
            minutes = "Min.",
            deliverTo = "Wohin sollen wir es bringen?",
            room = "Zimmer %s",
            spotNumber = "Nummer der %s",
            youAreAt = "Sie sind hier: %s",
            payment = "Zahlung",
            roomCharge = "Auf Zimmer %s buchen",
            card = "Kredit- oder Debitkarte",
            cardSoon = "Kommt mit dem Zahlungsanbieter",
            confirmCharge = "Ich bestätige die Buchung von %1\$s auf Zimmer %2\$s.",
            placeOrder = "Bestellung bestätigen",
            placing = "Wird gesendet…",
            placed = "Bestellung gesendet!",
            placedHint = "Wir sagen Bescheid, wenn sie unterwegs ist.",
            orderFailed = "Die Bestellung konnte nicht gesendet werden. Bitte erneut versuchen.",
            connectToOrder = "Verbinden Sie Ihr Handy mit dem TV Ihres Zimmers, um zu bestellen.",
            notAvailableHere = "An diesem Ort nicht verfügbar",
            cancelOrder = "Bestellung stornieren",
            viewOrders = "Meine Bestellungen ansehen",
            keepBrowsing = "Weiter stöbern",
            statusUpdate = "Ihre Bestellung %1\$s: %2\$s",
            demoGuest = "Testmodus: Die Bestellung läuft von selbst weiter. Mit dem Backend bewegt sie das Personal.",
            requested = "Eingegangen",
            accepted = "Angenommen",
            onTheWay = "Unterwegs",
            delivered = "Geliefert",
            cancelled = "Storniert",
            staffTitle = "Bestellungen",
            tabNew = "Neu",
            tabActive = "In Arbeit",
            tabDone = "Geliefert",
            accept = "Annehmen",
            startDelivery = "Losgehen",
            markDelivered = "Als geliefert markieren",
            chargeTo = "Buchung auf Zimmer %s",
            paidByCard = "Mit Karte bezahlt",
            chargeRegistered = "Auf Zimmer %s gebucht",
            guest = "Gast",
            minutesAgo = "vor %d Min.",
            justNow = "gerade eben",
            qrCodes = "QR-Codes",
            qrHint = "Drucken Sie jeden Code aus und kleben Sie ihn an seine Liege oder seinen Tisch: Der Gast scannt ihn und die Bestellung kommt mit dem Ort an.",
            emptyQueue = "Hier gibt es keine Bestellungen.",
            demoStaff = "Testmodus: Das sind Beispielbestellungen. Mit dem Backend kommen hier die der Gäste an.",
            back = "Zurück",
        )
    }
}
